kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ceph-rbd
  namespace: default
  annotations: 
    storageclass.kubernetes.io/is-default-class: "true"
    #storageclass.kubernetes.io/is-default-class: "false"非默认存储
provisioner: ceph.com/rbd
reclaimPolicy: Retain
#reclaimPolicy: Delete 回收
parameters:
  #ceph 管理节点ip
  monitors: 192.168.70.42:6789,192.168.70.43:6789,192.168.70.44:6789
  adminId: admin
  adminSecretName: storage-secret
  adminSecretNamespace: default
  pool: rbd
  fsType: xfs
  userId: admin
  userSecretName: storage-secret
  imageFormat: "2"
  imageFeatures: "layering"
